### PR TITLE
Add a build system

### PR DESCRIPTION
**Pull request by Jackymancs4**
Hello @zombieFox 
I've been using nightTab (web version) as my homepage for quite some time now, and I love it! Thank you for this!

But as others have noted, on my worst network condition, the site tend to lag/glitch on load time, most likely because of the many little connection it has to do.

So, here my take on #58 

The workflow is simple:
you develop as usual on `src` and when ready you run 
```
$ npm run build
```

to find in `build/web` the site with both css and js minified ready to be push both manually or automatically through a CI service (like travis) to the `gh_pages` branch, and in `build/webext` a zip file generated by `web-ext` (https://github.com/mozilla/web-ext) ready to be pushed to the markets.

The webextension package is not minified, but just a copy of `src`

Right now the culprits of this are:

1. if you add or remove a js file, you need to properly register or remove it from `gulpfile.js`
2. the comments I added in `index.html` are needed in order to replace all the references with their singleton counterparts, so they must be kept.

I based the PR on your 'gulp' branch.

### CODE REVIEW

**Comment by zombieFox** [comment]
Thanks for the PR. Looks great! Testing the branch it looks like the webext zip file produced does not have a minified `js` or `css` file. I'll see if I can change that.

**Comment by Jackymancs4** [comment]
> zip file produced does not have a minified js or css file.

Yes, that was intentional as AMO reviewers tend to complain about minimized files, and the extension being locally loaded should suffer minimal overhead.

I can change it if you prefer.

**Comment by zombieFox** [comment]
Ah, I was already pushing changes. Please let me know what you think of the changes.

**Comment by zombieFox** [comment]
One of the goals of the gulp and build tool ticket was to reduce load times as much as possible to help address the "white flash" issue on load.

**Comment by Jackymancs4** [comment]
> Please let me know what you think of the changes.

If it works for you it's good for me!
Maybe, the way you populate `folder` seems a little of an overkill to me, but that's just my opinion.

> One of the goals of the gulp and build tool ticket was to reduce load times as much as possible to help address the "white flash" issue on load.

Yes, that is affecting me, too, but I only used the web version so I didn't think to much for the web-ext, assuming it already loaded way faster.

**Comment by Jackymancs4** [comment]
Also, as an experiment, even the HTML could be minimized as you can test here https://github.com/Jackymancs4-Fork/nightTab/tree/feature/minimize-html

Current index.html: 74.7 kB (74713 B)
Minimized index.html: 56.7 kB (56744 B)
Size reduction: 25%

**Comment by zombieFox** [comment]
> Also, as an experiment, even the HTML could be minimized as you can test here 
Awesome, I've added that too. Good to merge. Thanks for the super help 👍

**Pull request merged**
